import './style.css';
import { blankWorkshop, exampleWorkshop, roles, type Card, type Role, type Workshop } from './types';

const KEY = 'ccw:workshop:v1';
const LICENSE_KEY = 'sb_license:concept-card-workshop';
const VERDICT_KEY = 'sb_license_verdict:concept-card-workshop';
const q = <T extends Element>(selector: string, root: ParentNode = document) => root.querySelector<T>(selector);
const uid = () => crypto.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(16).slice(2)}`;
let workshop: Workshop = load(); let selected: string | null = workshop.cards[0]?.id ?? null;
let elapsed = 0; let ticking: number | undefined; let liveCode = '';

function load(): Workshop { try { const saved = localStorage.getItem(KEY); return saved ? JSON.parse(saved) as Workshop : blankWorkshop(); } catch { return blankWorkshop(); } }
function save() { localStorage.setItem(KEY, JSON.stringify(workshop)); render(); }
function esc(s: string) { const d = document.createElement('div'); d.textContent = s; return d.innerHTML; }
function selectedCard() { return workshop.cards.find(c => c.id === selected); }
function cardMarkup(card: Card, mode = '') { const r = roles[card.role]; return `<article class="concept-card ${card.role} ${selected === card.id ? 'selected' : ''}" data-card="${card.id}" tabindex="0"><span class="role-mark" aria-hidden="true">${r.mark}</span><p class="eyebrow">${r.label}</p><h3>${esc(card.title || 'Untitled card')}</h3><p>${esc(card.body || r.prompt)}</p>${mode ? '' : '<span class="edit-hint">Edit card</span>'}</article>`; }
function emptyMarkup() { return `<section class="empty" aria-label="Empty workshop"><span aria-hidden="true">▣</span><h2>Build the first reasoning round</h2><p>Add a scenario, then layer evidence, a decision, and a consequence. The cards stay in this browser.</p><button class="primary" data-action="add" data-role="scenario">Add a scenario card</button><button class="quiet" data-action="example">Load a sample round</button></section>`; }
function render() {
  const app = q<HTMLDivElement>('#app')!; const card = selectedCard(); const isEmpty = workshop.cards.length === 0;
  app.innerHTML = `<header class="top"><a class="brand" href="/" aria-label="Concept Card Workshop home"><span aria-hidden="true">▦</span> CONCEPT CARD<br><b>WORKSHOP</b></a><nav aria-label="Product"><a href="#how">How it runs</a><button class="quiet" data-action="project">Project</button><button class="quiet" data-action="print">Print cards</button><button class="license-button" data-action="license">Offline packs <span aria-hidden="true">↗</span></button></nav></header>
  <main id="main"><section class="hero"><div><p class="kicker">A 15-minute discussion game</p><h1>Turn a lecture into a room full of <em>defensible decisions.</em></h1><p class="lede">Make scenario, evidence, decision, and consequence cards. Print them, deal them out, and run the debrief—no student accounts or scoring queue.</p><div class="hero-actions"><button class="primary" data-action="add" data-role="scenario">${isEmpty ? 'Start a card set' : 'Add a card'}</button><button class="quiet" data-action="example">Use the sample</button></div></div><figure><img src="/tabletop.webp" width="960" height="640" fetchpriority="high" decoding="async" alt="Pixel-art tabletop with four colourful stacks of discussion cards and a timer"/><figcaption>Original AI-generated illustration · cards are blank until you write them.</figcaption></figure></section>
  <section class="workbench" aria-label="Workshop composer"><aside class="setup"><p class="eyebrow">Set up</p><label>Workshop title<input id="workshop-title" value="${esc(workshop.title)}" maxlength="80" /></label><label>Discussion time <output id="minutes-value">${workshop.minutes} minutes</output><input id="minutes" type="range" min="5" max="30" step="5" value="${workshop.minutes}" aria-label="Discussion time in minutes" /></label><div class="role-guide">${(Object.keys(roles) as Role[]).map(role => `<button class="role-key ${role}" data-action="add" data-role="${role}"><span>${roles[role].mark}</span><b>${roles[role].label}</b><small>${roles[role].prompt}</small></button>`).join('')}</div><button class="danger-link" data-action="clear">Clear this set</button></aside>
  <section class="canvas"><div class="canvas-head"><div><p class="eyebrow">Card set · ${workshop.cards.length} ${workshop.cards.length === 1 ? 'card' : 'cards'}</p><h2>${esc(workshop.title)}</h2></div><div class="save-note" aria-live="polite">Saved on this device</div></div><div class="card-grid">${isEmpty ? emptyMarkup() : workshop.cards.map(c => cardMarkup(c)).join('')}</div></section>
  <aside class="editor" aria-label="Card editor">${card ? `<p class="eyebrow">Editing ${roles[card.role].label}</p><label>Card role<select id="card-role">${(Object.keys(roles) as Role[]).map(r => `<option value="${r}" ${r === card.role ? 'selected' : ''}>${roles[r].mark} ${roles[r].label}</option>`).join('')}</select></label><label>Short title<input id="card-title" value="${esc(card.title)}" maxlength="60" /></label><label>Discussion prompt<textarea id="card-body" rows="7" maxlength="480">${esc(card.body)}</textarea></label><p class="editor-tip">Ask for a choice and the evidence behind it. Keep one idea per card.</p><button class="danger" data-action="delete" data-id="${card.id}">Remove this card</button>` : `<p class="eyebrow">Card editor</p><p class="editor-placeholder">Select a card to revise it. Your materials never leave this device.</p>`}</aside></section>
  <section class="run-strip" id="how"><div><p class="eyebrow">Facilitator clock</p><output class="timer" aria-live="off">${clock()}</output><p>${ticking ? 'Round is running.' : elapsed ? 'Clock paused.' : `Set for ${workshop.minutes} minutes.`}</p></div><div class="timer-actions"><button class="primary" data-action="timer">${ticking ? 'Pause clock' : elapsed ? 'Resume clock' : 'Start round'}</button><button class="quiet" data-action="reset">Reset</button></div><ol><li>Deal one scenario and evidence card.</li><li>Groups make a decision and defend it.</li><li>Use a consequence card to debrief.</li></ol></section>
  <section class="share-grid"><article><p class="eyebrow">Optional projection</p><h2>Put the cards on a shared screen.</h2><p>Open a clean projection view with a no-account code and a shareable link. The deck is packed into the link—no class data is sent to a server.</p><button class="primary" data-action="project">Open projection view</button></article><article><p class="eyebrow">Free to use</p><h2>One complete card set, printing, timer, and projection.</h2><p>Need a field-ready offline template pack? A one-time $12 unlock adds downloadable blank pack templates without gating your cards or exports.</p><button class="quiet" data-action="license">See offline packs</button></article></section></main>
  <footer><span>Made for instructor-led reasoning, not student profiling.</span><span><a href="/privacy/">Privacy</a> · <a href="/terms/">Terms</a></span></footer>`;
  bind();
}
function bind() {
  q<HTMLInputElement>('#workshop-title')?.addEventListener('change', e => { workshop.title = (e.target as HTMLInputElement).value.trim() || 'Untitled workshop'; save(); });
  q<HTMLInputElement>('#minutes')?.addEventListener('input', e => { workshop.minutes = Number((e.target as HTMLInputElement).value); q('#minutes-value')!.textContent = `${workshop.minutes} minutes`; });
  q<HTMLInputElement>('#minutes')?.addEventListener('change', () => { elapsed = 0; save(); });
  q<HTMLSelectElement>('#card-role')?.addEventListener('change', e => { const c = selectedCard(); if (c) { c.role = (e.target as HTMLSelectElement).value as Role; save(); } });
  for (const [id, key] of [['#card-title', 'title'], ['#card-body', 'body']] as const) q<HTMLInputElement | HTMLTextAreaElement>(id)?.addEventListener('input', e => { const c = selectedCard(); if (c) { c[key] = (e.target as HTMLInputElement).value; localStorage.setItem(KEY, JSON.stringify(workshop)); const found = q(`[data-card="${c.id}"] h3`); if (key === 'title' && found) found.textContent = c.title || 'Untitled card'; } });
  q<HTMLInputElement>('#card-title')?.addEventListener('change', save); q<HTMLTextAreaElement>('#card-body')?.addEventListener('change', save);
  document.querySelectorAll<HTMLElement>('[data-card]').forEach(el => { const open = () => { selected = el.dataset.card!; render(); }; el.addEventListener('click', open); el.addEventListener('keydown', e => { if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); open(); } }); });
  document.querySelectorAll<HTMLButtonElement>('[data-action]').forEach(b => b.addEventListener('click', () => act(b.dataset.action!, b.dataset)));
}
function act(action: string, data: DOMStringMap) {
  if (action === 'add') { const role = data.role as Role; const r = roles[role]; const c: Card = { id: uid(), role, title: '', body: r.prompt }; workshop.cards.push(c); selected = c.id; save(); }
  if (action === 'example') { workshop = exampleWorkshop(); selected = workshop.cards[0].id; elapsed = 0; save(); }
  if (action === 'delete' && data.id) { workshop.cards = workshop.cards.filter(c => c.id !== data.id); selected = workshop.cards[0]?.id ?? null; save(); }
  if (action === 'clear' && confirm(`Clear all ${workshop.cards.length} cards? This cannot be undone.`)) { workshop = blankWorkshop(); selected = null; elapsed = 0; save(); }
  if (action === 'timer') toggleTimer(); if (action === 'reset') { elapsed = 0; stopTimer(); render(); }
  if (action === 'print') printCards(); if (action === 'project') openProjector(); if (action === 'license') licenseDialog();
}
function clock() { const left = Math.max(0, workshop.minutes * 60 - elapsed); return `${String(Math.floor(left / 60)).padStart(2, '0')}:${String(left % 60).padStart(2, '0')}`; }
function toggleTimer() { if (ticking) { stopTimer(); render(); return; } ticking = window.setInterval(() => { elapsed++; if (elapsed >= workshop.minutes * 60) { stopTimer(); alert('Round complete. Bring the room back for the debrief.'); } render(); }, 1000); render(); }
function stopTimer() { if (ticking) window.clearInterval(ticking); ticking = undefined; }
function printCards() { if (!workshop.cards.length) { alert('Add at least one card before printing.'); return; } const w = window.open('', '_blank'); if (!w) { alert('Your browser blocked the print window. Allow pop-ups and try again.'); return; } w.document.write(`<!doctype html><html lang="en"><title>${esc(workshop.title)} cards</title><style>body{font-family:Arial,sans-serif;color:#171b2a;margin:20px}h1{font-size:22px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.card{border:2px solid #171b2a;padding:14px;min-height:180px;break-inside:avoid}.scenario{border-top:10px solid #8cf4ff}.evidence{border-top:10px solid #8ee1b0}.decision{border-top:10px solid #ffcf70}.consequence{border-top:10px solid #ff886f}small{text-transform:uppercase;font-weight:bold}@media print{body{margin:10mm}.card{min-height:72mm}} </style><h1>${esc(workshop.title)}</h1><p>Facilitator copy · deal, discuss, defend, debrief.</p><div class="grid">${workshop.cards.map(c => `<section class="card ${c.role}"><small>${roles[c.role].label}</small><h2>${esc(c.title || 'Untitled card')}</h2><p>${esc(c.body)}</p></section>`).join('')}</div><script>window.onload=()=>window.print()<\/script></html>`); w.document.close(); }
function encode(work: Workshop) { return btoa(unescape(encodeURIComponent(JSON.stringify(work)))); }
function openProjector() { if (!workshop.cards.length) { alert('Add cards before opening a projection view.'); return; } liveCode = Math.random().toString(36).slice(2, 8).toUpperCase(); const url = `${location.origin}${location.pathname}?project=${liveCode}#deck=${encode(workshop)}`; window.open(url, '_blank', 'noopener'); }
function projection() { const data = location.hash.match(/deck=([^&]+)/)?.[1]; if (!data) return false; try { workshop = JSON.parse(decodeURIComponent(escape(atob(data)))) as Workshop; } catch { return false; } const code = new URLSearchParams(location.search).get('project') || 'LOCAL'; document.title = `${workshop.title} — projection`; q('#app')!.innerHTML = `<main class="projection"><p class="kicker">CONCEPT CARD WORKSHOP · JOIN CODE ${esc(code)}</p><h1>${esc(workshop.title)}</h1><p class="projection-lede">Deal a card. Name the evidence. Defend a decision.</p><div class="projection-cards">${workshop.cards.map(c => cardMarkup(c, 'project')).join('')}</div><p class="project-note">Share this exact link to show the same cards. No accounts and no server storage.</p></main>`; return true; }
function unlocked() { try { const verdict = JSON.parse(localStorage.getItem(VERDICT_KEY) || 'null') as { valid?: boolean } | null; return verdict?.valid === true; } catch { return false; } }
function licenseDialog() { const old = q<HTMLDialogElement>('#license-dialog'); if (old) old.showModal(); else { const d = document.createElement('dialog'); d.id = 'license-dialog'; const pack = unlocked() ? '<button class="primary" value="default" data-pack>Download blank field pack</button>' : '<a class="primary linkbutton" href="https://api.sociobot.in/api/v1/products/concept-card-workshop/checkout">Buy one-time unlock</a>'; d.innerHTML = `<form method="dialog"><button class="close" aria-label="Close">×</button><p class="eyebrow">Offline pack templates</p><h2>Print-ready field kits for $12, once.</h2><p>Get blank facilitation-pack layouts for offline professional training. Your free card set, printing, accessibility, and export remain available without it.</p>${pack}<label>Have a license? Paste it<input id="license-input" autocomplete="off" /></label><button class="quiet" value="default" data-restore>Restore license</button><p id="license-status" aria-live="polite"></p><small>Sociobot / Dodo is merchant of record. Refunds revoke the unlock. <a href="/terms/">Terms</a></small></form>`; document.body.append(d); d.querySelector('[data-restore]')?.addEventListener('click', e => { e.preventDefault(); const token = q<HTMLInputElement>('#license-input', d)?.value.trim(); if (!token) { q('#license-status', d)!.textContent = 'Paste your license token first.'; return; } localStorage.setItem(LICENSE_KEY, token); q('#license-status', d)!.textContent = 'License saved. Checking it in the background…'; verifyLicense(token); }); d.querySelector('[data-pack]')?.addEventListener('click', e => { e.preventDefault(); offlinePack(); }); d.showModal(); } }
function offlinePack() { const w = window.open('', '_blank'); if (!w) return; w.document.write(`<!doctype html><html lang="en"><title>Blank facilitation field pack</title><style>body{font-family:Arial,sans-serif;margin:12mm;color:#171b2a}h1{font-size:22px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:9mm}.card{min-height:78mm;border:2px solid #171b2a;padding:8mm}.scenario{border-top:9px solid #29aebb}.evidence{border-top:9px solid #299c68}.decision{border-top:9px solid #cc9217}.consequence{border-top:9px solid #ce5748}small{font-weight:bold;text-transform:uppercase}@media print{body{margin:8mm}}</style><h1>Blank facilitation field pack</h1><p>Write one idea per card. Deal → discuss → defend → debrief.</p><div class="grid">${(['scenario', 'evidence', 'decision', 'consequence'] as Role[]).flatMap(role => Array.from({ length: 3 }, () => `<section class="card ${role}"><small>${roles[role].label}</small><h2>________________</h2><p>____________________________________________________</p><p>____________________________________________________</p></section>`)).join('')}</div><script>window.onload=()=>window.print()<\/script></html>`); w.document.close(); }
async function verifyLicense(token: string) { try { const r = await fetch(`https://api.sociobot.in/api/v1/products/concept-card-workshop/verify?license=${encodeURIComponent(token)}`); const answer = await r.json() as { valid: boolean }; localStorage.setItem(VERDICT_KEY, JSON.stringify({ ...answer, checked: Date.now() })); const status = q('#license-status'); if (status) status.textContent = answer.valid ? 'Offline packs unlocked.' : 'License is not active. You can still use every free workshop tool.'; } catch { /* offline: cached access is never a blocker */ } }
function checkLicense() { const p = new URLSearchParams(location.search); const token = p.get('license'); if (token) { localStorage.setItem(LICENSE_KEY, token); p.delete('license'); history.replaceState({}, '', `${location.pathname}${p.size ? `?${p}` : ''}${location.hash}`); } const stored = localStorage.getItem(LICENSE_KEY); const cached = localStorage.getItem(VERDICT_KEY); if (stored && (!cached || Date.now() - JSON.parse(cached).checked > 86400000)) void verifyLicense(stored); }
if (!projection()) { checkLicense(); render(); }
if ('serviceWorker' in navigator) window.addEventListener('load', () => void navigator.serviceWorker.register('/sw.js'));
